### ISSUE TITLE
Issue with defining asrtimeout

### ISSUE THREAD

**Issue by kenmiller316** [tobyriddell/puppet-conrep#1]
Hi,
I believe there might be a parsing error with asrtimeout due to the fact that it's values have an embedded space.  In trying various attempts, I'm continually having ILO reply that the value must be 5 Minutes even though it reports I attempted 5 Minutes.  Here's what I've attempted:

5 Minutes
'5 Minutes'
"5 Minutes"
5_Minutes
5
5M
5Min

All to no avail.  Any tricks to getting this setting a value?

Thanks,

== k+ ==

**Comment by tobyriddell** [comment]
Hmm... I've had some issues with interpreting values with leading digits as
numbers, that may be what's happening here. What version of Puppet are you
using? Are you also using Hiera?

Could you try this on the server you're configuring the BIOS on:

puppet apply -e 'conrep {"default": asrtimeout => "5 Minutes"}'

Also try:

puppet resource conrep | grew asrtimeout

And let me see the results?

**Comment by kenmiller316** [comment]
Hi,

Thanks very much for the quick reply.  I'm using Puppet 4.10 and applying against a DL3460 G7  ROM 08/16/2015 (P68) (different network).  And yes, I'm using hiera extensively.

The key resulting lines of puppet apply -e 'conrep {"default": asrtimeout => "5 Minutes"}' are:
ERROR: Unsupported content '5 Minutes' for data file section 'OS'
Conrep return code: 2

I'm also debugging a curious error on first execution after provisioning (but does not throw this error with subsequent runs):
Error: Failed to apply catalog: undefined method `conrep for Puppet::Type::Conrep::ProviderConrep:Class

I mention this because the results of a 'puppet resource conrep' resulted in:
Error: Could not run: Could not find type conrep

Even though the puppet log clearly showed that a conrep resource type was successfully processed in the command immediately prior to this command; namely:
Notice: /Stage[main]/Hw_hp/Conrep[default]/videooptions changed Optional_Primary_embedded_Disabled to Embedded_primary_Optional_Secondary

I thought perhaps both items might be related and thus provide you clues for what's going on. ;)

Thanks again!

**Comment by kenmiller316** [comment]
oh, I forgot to mention, we're using Open Source puppet in a "master-less" environment (e.g. no agents, only 'puppet apply').

**Comment by tobyriddell** [comment]
Ok, I think the issue is that the conrep binary is not being found. Is it
in your PATH?

On Nov 18, 2017 12:20 PM, "kenmiller316" <notifications@github.com> wrote:

oh, I forgot to mention, we're using Open Source puppet in a "master-less"
environment (e.g. no agents, only 'puppet apply').

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tobyriddell/puppet-conrep/issues/1#issuecomment-345456745>,
or mute the thread

**Comment by kenmiller316** [comment]
Hi,
That solves:
Error: Failed to apply catalog: undefined method `conrep for Puppet::Type::Conrep::ProviderConrep:Class

Specifically, I have to install hp-scripting-tools *before* executing puppet that asks for a conrep variable, thanks!

Any thoughts on the asrtimeout => "5 Minutes"}' error?

**Comment by tobyriddell** [comment]
Yes, puppet is executing the conrep binary under the hood to first extract
the BIOS settings in the form of an XML file, and then if any settings need
changing it generates a new XML file and loads it, once again with conrep.

Just so I'm clear: 'puppet apply ...' is working on the command line now?

Since you're getting the "5 Minutes" setting via hiera, could you try
putting quotes around it in the YAML?


On Nov 18, 2017 1:48 PM, "kenmiller316" <notifications@github.com> wrote:

Hi,
That solves:

Error: Failed to apply catalog: undefined method `conrep for
Puppet::Type::Conrep::ProviderConrep:Class

Specifically, I have to install hp-scripting-tools *before* executing
puppet that asks for a conrep variable, thanks!

Any thoughts on the asrtimeout => "5 Minutes"}' error?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tobyriddell/puppet-conrep/issues/1#issuecomment-345462479>,
or mute the thread

**Comment by kenmiller316** [comment]
Hi,

No, the puppet apply of asrtimeout still fails.  Namely,
The key resulting lines of puppet apply -e 'conrep {"default": asrtimeout => "5 Minutes"}' are:
ERROR: Unsupported content '5 Minutes' for data file section 'OS'
Conrep return code: 2

**Comment by kenmiller316** [comment]
but 'puppet resource conrep' works, though there's no value for asrtimeout, only asr.

**Comment by tobyriddell** [comment]
Aha! This is interesting... can you run conrep by hand and inspect the
output? From memory it's invoked as:

conrep -s -f foo.xml

Then 'grep -i timeout foo.xml' (the actual parameter in the XML file will
be spelled something like 'ASR_timeout')

It's possible there's no such parameter on your model of server.

**Comment by kenmiller316** [comment]
Hi,

conrep -s -f foo.xml| reveals an ASR_Timeout record whose value is 5 Minutes (no quotes intentional).  Specifically it is delimitted by '...>' and '</Section>, as in:
>5 Minutes</Section> .

I've tried updating it to 10 Minutes (in case it needed to have a change value or error), but to no avail.

**Comment by tobyriddell** [comment]
OK. I'll try to summarise what we know so far:

1. "puppet resource conrep" produces output that does not contain
'asrtimeout'
2. When conrep is used to extract the BIOS settings as XML, using "conrep
-s -f foo.xml", the resulting file contains a setting for 'ASR_timeout'

If you run "conrep -s -f foo.xml", can you make the resulting foo.xml file
available to me somehow? Perhaps via https://gist.github.com? It sounds
like the Puppet provider is failing to parse it somehow.

**Comment by kenmiller316** [comment]
Unfortunately I'm working in a lab without internet access.  
However,  I added some puts to your conrep.rb file to dump the xml code you're generating and I found a line with:
<Section name=<Section name=5 Minutes</Section> 
which is not complete.  It should be:
<Section name="ASR_Timeout>5 Minutes</Section>

And this is causing conrep to fail as above.

**Comment by kenmiller316** [comment]
Grrr... this GUI ate the most important lines!

The errant line is '<Section name=>5 Minutes</Section>' when it should be '<Section name="ASR_Timeout">5 Minutes</Section>'

**Comment by kenmiller316** [comment]
Grrr... this GUI ate the most important lines!

The errant line is:

> \<Section name=>5 Minutes\</Section>

when it should be :

> \<Section name="ASR_Timeout">5 Minutes\</Section>

**Comment by kenmiller316** [comment]
I think the issue is not the blanks, but rather the section name 'ASR' causes the section name 'ASR_Timeout' not to be saved.  A couple of well-placed puts in conrep.rb revealed that there is no 'ASR_Timeout' value in section.attributes[name] which tells me that the REXML::Document.new call did not correctly populate it, though a puts of the XML document being read shows it is there.

**Comment by tobyriddell** [comment]
Ah, this is very interesting. So something is going wrong in the XML parser?

As a quick test I tried creating a dummy XML file containing:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Conrep>
<Section name="ASR" helptext="Allows foo vs. bar">Disabled</Section>
<Section name="ASR_timeout" helptext="Allows foo vs. bar">10 Minutes</Section>
</Conrep>
```

And then ran the following script (it's basically the parts from provider/conrep/conrep.rb that process the XML and turn the section name into a valid Puppet parameter name):

```ruby
#!/usr/bin/ruby

require 'rexml/document'

xmlData = File.read('dummy.xml')
doc = REXML::Document.new xmlData

$map2Valid = {}
def self.makeValid(invalid)
  if ! $map2Valid.has_key?(invalid)
    # Make into a valid puppet symbol by:
    # 1) Removing special characters
    # 2) Prepending 'i' if it starts with digits
    # 3) Removing dots if it ends with dots + numbers
    valid = invalid.gsub(/[- ()_\/:;,]/,'').sub(/^([0-9]+)/, 'i\1').sub(/\.([0-9]+)$/, '\1')
    $map2Valid[invalid] = valid
  end
  $map2Valid[invalid]
end

doc.elements.each('/Conrep/Section') do |section|
  puts makeValid(section.attributes['name'].downcase).to_sym
end
```

The output is:

```
asr
asrtimeout
```

So that seems to be working fine.

Can you check the XML file that is generated by the conrep binary (conrep -s -f /tmp/foo.xml) and see if it contains any special characters, especially in the vicinity of the 'ASR_timeout' section? I'm wondering if there's something there that's upsetting the XML parser.

**Comment by tobyriddell** [comment]
Hi @kenmiller316, 

Were you able to check the XML output from conrep?

**Comment by kenmiller316** [comment]
I hope to be able to run it tomorrow.  Sorry for the delay.

**Comment by kenmiller316** [comment]
Hi tobyriddell,
I tried you program against conrep output and it successfully parsed everything including asr/asrtimeout .  So the XML parsing does not appear to be the problem.

**Comment by tobyriddell** [comment]
Sorry for the delayed in responding... there seems to be some discrepancy here. Previously you mentioned that conrep produced an output file containing an incomplete element, i.e.:

```xml
<Section name=>5 Minutes</Section>
```

But on the other hand your most recent update says that the Ruby snippet parses the conrep output correctly (and sees asrtimeout, as expected). It can't do this unless there's valid "ASR_Timeout" string in the XML, which wasn't there previously. It seems that the conrep binary is being inconsistent with the output it produces! So I think the issue may be with the conrep binary rather than with the Puppet code... what do you reckon?

**Comment by tobyriddell** [comment]
I'm going to close this issue - no response for 1 month. Please feel free to reopen if you think there's more investigation worth doing.

I believe the summary is that there's an issue (possible an intermittent issue) with the generated XML. And without being able to see the full XML it's not possible to determine the exact problem.
